const LOCATIONS=[
['飞机','机长，空乘人员，头等舱乘客，经济舱乘客，航空安全员，机械师，副驾驶'],['银行','银行经理，出纳员，保安，运钞车司机，办理业务的顾客，投资顾问，金库管理员'],['海滩','救生员，冲浪爱好者，冰淇淋小贩，日光浴游客，游泳教练，摄影师，清洁工'],['赌场','赌场经理，荷官，赌徒，保安，调酒师，筹码兑换员，驻唱歌手'],['医院','外科大夫，护士，病人，麻醉师，医院院长，清洁工，探病家属'],['酒店','酒店经理，前台接待，门童，保洁员，厨师，旅客，调酒师'],['军事基地','基地指挥官，狙击手，新兵，军医，炊事班长，通信兵，武器教官'],['电影片场','导演，男主角，女主角，摄像师，化妆师，场务，特技替身'],['豪华游轮','船长，轮机长，游客，厨师，餐厅服务员，驻唱歌手，赌场荷官'],['客运火车','列车长，乘务员，餐饮推车售货员，乘客，司机，检票员，乘警'],['海盗船','海盗船长，大副，炮手，舵手，厨子，被俘虏的贵族，水手'],['极地科考站','站长，冰川学家，气象学家，医生，通讯员，直升机驾驶员，厨师'],['警察局','局长，刑警，巡警，犯罪嫌疑人，报案市民，法医，档案管理员'],['高档餐厅','主厨，餐厅经理，服务员，迎宾员，顾客，美食评论家，侍酒师'],['学校','校长，老师，学生，门卫，食堂阿姨，教导主任，校医'],['太空站','宇航员，空间站指挥官，工程师，科学家，医生，外星生物学家，通讯员'],['潜艇','潜艇艇长，声纳员，鱼雷操作员，轮机长，厨师，军医，通信兵'],['超市','店长，收银员，理货员，顾客，生鲜区屠夫，试吃推销员，库管员'],['剧院','舞台导演，话剧演员，灯光师，售票员，观众，剧院经理，提词员'],['动物园','园长，兽医，饲养员，售票员，游客，导游，动物摄影师']
].map(([name,roles])=>({name,roles:roles.split('，')}));
const app=document.querySelector('#app');let state={screen:'home',count:0,players:[],selected:null,secretVisible:false,timer:480,paused:true,ended:false};let timerId;
const pick=a=>a[Math.floor(Math.random()*a.length)];const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function newRound(){const location=pick(LOCATIONS),spy=Math.floor(Math.random()*state.count),roles=shuffle(location.roles);state.players=Array.from({length:state.count},(_,i)=>({name:`玩家${i+1}`,done:false,spy:i===spy,role:i===spy?null:roles.shift(),location:location.name}));state.selected=null;state.secretVisible=false;state.screen='lobby';render()}
function home(){clearInterval(timerId);state={screen:'home',count:0,players:[],selected:null,secretVisible:false,timer:480,paused:true,ended:false};render()}
function render(){if(state.screen==='home')return renderHome();if(state.screen==='lobby')return renderLobby();if(state.screen==='confirm')return renderConfirm();if(state.screen==='ready')return renderReady();renderTimer()}
function shell(content){app.innerHTML=`<div class="brand"><div class="eyebrow">CLASSIFIED // PARTY GAME</div><h1>间谍危机</h1><div class="muted">SPYFALL</div></div>${content}<div class="footer">本局信息仅保存在这台手机上</div>`}
function renderHome(){shell(`<section class="panel"><h2>选择玩家人数</h2><div class="choices">${[3,4,5,6,7,8].map(n=>`<button class="choice ${state.count===n?'selected':''}" data-count="${n}">${n}人</button>`).join('')}</div><button class="primary" id="start" ${state.count?'':'disabled'}>开始游戏</button></section>`);document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{state.count=+b.dataset.count;render()});document.querySelector('#start').onclick=newRound}
function renderLobby(){shell(`<section class="panel"><h2>选择你的玩家编号</h2><div class="notice">请按顺序传阅手机。已查看的玩家会被锁定，不能再次打开身份。</div><div class="player-list" style="margin-top:16px">${state.players.map((p,i)=>`<button class="player-card ${p.done?'done':''}" data-player="${i}" ${p.done?'disabled':''}><span>${p.done?'✓ ':''}${p.name}</span><span class="badge">${p.done?'已查看':'点击查看'}</span></button>`).join('')}</div></section>`);document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.player;state.secretVisible=false;state.screen='confirm';render()})}
function backToLobby(){state.secretVisible=false;state.selected=null;state.screen='lobby';render()}
function renderConfirm(){const p=state.players[state.selected];shell(`<section class="panel confirm"><div class="topbar"><button class="back" id="back">← 返回</button></div><h2>你是 ${p.name}</h2>${state.secretVisible?secretMarkup(p):`<p class="muted">确认其他人看不到屏幕后查看身份</p><div class="redact">身份已加密</div><button class="primary" id="view">查看身份</button>`}</section>`);document.querySelector('#back').onclick=backToLobby;if(state.secretVisible){document.querySelector('#remember').onclick=()=>{p.done=true;state.secretVisible=false;state.selected=null;state.screen=state.players.every(x=>x.done)?'ready':'lobby';render()}}else{document.querySelector('#view').onclick=()=>{state.secretVisible=true;render()}}}
function secretMarkup(p){return `<div class="secret">${p.spy?`<h2>🕵️ 你是间谍</h2><p class="muted">地点：未知<br>角色：未知</p><p class="notice">从其他人的提问和回答中判断大家在哪里。</p>`:`<div class="label">地点</div><div class="place">${p.location}</div><div class="label">职业</div><div class="role">${p.role}</div>`}</div><button class="primary" id="remember">我记住了，关闭身份</button>`}
function renderReady(){const first=pick(state.players);shell(`<section class="panel center"><h2>所有身份已确认</h2><div class="notice">本局时间：08:00</div><p class="muted" style="margin:22px 0">首问玩家：<strong>${first.name}</strong></p><button class="primary" id="begin">开始游戏</button></section>`);document.querySelector('#begin').onclick=()=>{state.screen='timer';state.paused=false;state.timer=480;state.ended=false;startTimer();render()}}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{if(!state.paused&&!state.ended){state.timer--;if(state.timer<=0){state.timer=0;state.ended=true;state.paused=true;beep();}render()}},1000)}
function beep(){try{const c=new AudioContext(),o=c.createOscillator();o.connect(c.destination);o.frequency.value=660;o.start();o.stop(c.currentTime+.7)}catch(e){}}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function renderTimer(){shell(`<section class="panel timer ${state.ended?'timeout':''} ${!state.paused?'running':''}"><div class="muted">本局倒计时</div><div class="clock">${fmt(state.timer)}</div><div class="status">${state.ended?'时间到':state.paused?'已暂停':'进行中'}</div><div class="actions">${state.ended?`<button class="primary" id="again">再来一局</button><button class="secondary" id="home">返回首页</button>`:`<button class="primary" id="pause">${state.paused?'继续':'暂停'}</button><button class="danger" id="end">结束本局</button>`}</div></section>`);if(state.ended){document.querySelector('#again').onclick=newRound;document.querySelector('#home').onclick=home}else{document.querySelector('#pause').onclick=()=>{state.paused=!state.paused;render()};document.querySelector('#end').onclick=()=>{state.ended=true;state.paused=true;render()}}}
render();
